// GENERATED by scripts/compile-contract.ts (solc 0.8.36+commit.8a079791.Emscripten.clang) - do not edit.
import { parseAbi } from "viem";

export const escrowAbi = parseAbi([
  "constructor(address)",
  "event DisputeSet(bytes32 indexed milestoneKey,bool open)",
  "event EscrowFunded(bytes32 indexed milestoneKey,address payer,uint256 amount)",
  "event EscrowRefunded(bytes32 indexed milestoneKey,address receiver,uint256 amount)",
  "event EscrowReleased(bytes32 indexed milestoneKey,address receiver,uint256 amount)",
  "event FreelancerSet(bytes32 indexed milestoneKey,address freelancer)",
  "function escrows(bytes32) view returns (address,address,uint256,bool,bool,bool)",
  "function fund(bytes32) payable",
  "function guardian() view returns (address)",
  "function refund(bytes32)",
  "function release(bytes32)",
  "function setDispute(bytes32,bool)",
  "function setFreelancer(bytes32,address)"
]);
