import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

interface SolcJson {
  compile(inputJson: string): string;
  version(): string;
}

const require = createRequire(import.meta.url);
const solc = require("solc") as SolcJson;

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOLIDITY_PATH = resolve(PACKAGE_ROOT, "contracts", "MilestoneEscrow.sol");
const CONTRACT_NAME = "MilestoneEscrow";

const solcSources = {
  [SOLIDITY_PATH]: { content: await readFile(SOLIDITY_PATH, "utf8") },
};

const input = {
  language: "Solidity",
  sources: solcSources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: {
      "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object"] },
    },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input))) as {
  contracts?: Record<string, Record<string, { abi: unknown }>>;
  errors?: Array<{ severity: string; formattedMessage: string }>;
};

const fatalErrors = (output.errors ?? []).filter((error) => error.severity === "error");
if (fatalErrors.length > 0) {
  throw new Error(`Solidity compilation failed:\n${fatalErrors.map((error) => error.formattedMessage).join("\n")}`);
}

const contract = output.contracts?.[SOLIDITY_PATH]?.[CONTRACT_NAME];
if (!contract) {
  throw new Error(`Compiled contract ${CONTRACT_NAME} not found in output.`);
}

const abi = contract.abi as Array<{
  type: "function" | "event" | "constructor" | "error" | "fallback" | "receive";
  name?: string;
  inputs?: Array<{ type: string; indexed?: boolean; name?: string }>;
  outputs?: Array<{ type: string }>;
  stateMutability?: string;
}>;

const signatures = abi.map(toSignature).filter(Boolean);

const artifactDir = resolve(PACKAGE_ROOT, "dist", "contracts");
await mkdir(artifactDir, { recursive: true });

await writeFile(
  resolve(artifactDir, `${CONTRACT_NAME}.json`),
  `${JSON.stringify(
    {
      contractName: CONTRACT_NAME,
      compiler: solc.version(),
      abi,
      bytecode: `0x${contract.evm.bytecode.object}`,
    },
    null,
    2,
  )}\n`,
);

const generated = `// GENERATED by scripts/compile-contract.ts (solc ${solc.version()}) - do not edit.
import { parseAbi } from "viem";

export const escrowAbi = parseAbi(${JSON.stringify(signatures, null, 2)});
`;

await writeFile(resolve(PACKAGE_ROOT, "src", "escrow-abi.gen.ts"), generated);

console.log(`Compiled ${CONTRACT_NAME} (${solc.version()}): ${signatures.length} ABI signatures written.`);
console.log(`Artifact: ${resolve(artifactDir, `${CONTRACT_NAME}.json`)}`);

function toSignature(
  item: {
    type: string;
    name?: string;
    inputs?: Array<{ type: string; indexed?: boolean; name?: string }>;
    outputs?: Array<{ type: string }>;
    stateMutability?: string;
  },
): string | null {
  switch (item.type) {
    case "constructor":
      return `constructor(${(item.inputs ?? []).map((input) => input.type).join(",")})`;
    case "function": {
      const inputs = (item.inputs ?? []).map((input) => input.type).join(",");
      const mutability = item.stateMutability === "payable" ? " payable" : item.stateMutability === "view" ? " view" : "";
      const outputs =
        item.outputs && item.outputs.length > 0 ? ` returns (${item.outputs.map((output) => output.type).join(",")})` : "";
      return `function ${item.name}(${inputs})${mutability}${outputs}`;
    }
    case "event":
      return `event ${item.name}(${(item.inputs ?? [])
        .map((input) => paramSignature(input.type, input.indexed ?? false, input.name))
        .join(",")})`;
    default:
      return null;
  }
}

function paramSignature(typeName: string, indexed: boolean, name?: string): string {
  const indexModifier = indexed ? " indexed" : "";
  return `${typeName}${indexModifier}${name ? ` ${name}` : ""}`;
}